import importlib.util
from pathlib import Path
import tempfile
import unittest

spec = importlib.util.spec_from_file_location('prepare_native', Path(__file__).parents[1] / 'prepare-native.py')
native = importlib.util.module_from_spec(spec)
spec.loader.exec_module(native)


class NativeSourcesTest(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.repo = Path(self.temp.name)
        self.platform = self.repo / 'release/src-qca-ipq53xx'
        self.common = self.repo / 'release/src/router/example.c'
        self.common.parent.mkdir(parents=True)
        self.common.write_text('common source\n')
        self.platform.mkdir(parents=True)
        self.manifest = {'shared_files': ['release/src/router/example.c'], 'overlay_files': [],
                         'platform_files': [], 'platform_links': {'router': '../src/router'}}
        self.build = self.platform / '.build'

    def plan(self):
        return native.source_plan(self.repo, self.platform, self.manifest)

    def test_build_writes_do_not_change_shared_sources(self):
        self.assertEqual(native.materialize(self.repo, self.build, self.plan()), 2)
        built = self.build / 'source/release/src/router/example.c'
        built.write_text('generated by build\n')
        self.assertEqual(native.materialize(self.repo, self.build, self.plan()), 0)
        self.assertEqual(built.read_text(), 'generated by build\n')
        self.assertEqual(self.common.read_text(), 'common source\n')
        self.common.write_text('edited source\n')
        self.assertEqual(native.materialize(self.repo, self.build, self.plan()), 1)
        self.assertEqual(built.read_text(), 'edited source\n')

    def test_symlink_keeps_sdk_relative_layout(self):
        native.materialize(self.repo, self.build, self.plan())
        alias = self.build / 'source/release/src-qca-ipq53xx/router'
        self.assertTrue(alias.is_symlink())
        self.assertEqual((alias / 'example.c').read_text(), 'common source\n')

    def test_copy_order_cannot_invalidate_shipped_generated_files(self):
        stamp = self.platform / 'source-overlay/release/src/router/example.stamp'
        stamp.parent.mkdir(parents=True)
        stamp.write_text('stamp\n')
        self.manifest['overlay_files'] = ['release/src/router/example.stamp']
        native.materialize(self.repo, self.build, self.plan())
        directory = self.build / 'source/release/src/router'
        self.assertEqual((directory / 'example.c').stat().st_mtime_ns,
                         (directory / 'example.stamp').stat().st_mtime_ns)

    def test_missing_common_input_fails_before_staging(self):
        self.common.unlink()
        with self.assertRaisesRegex(ValueError, 'Missing source'):
            self.plan()
        self.assertFalse(self.build.exists())

    def test_overlay_does_not_replace_an_upstream_file(self):
        self.manifest['shared_files'] = []
        self.manifest['overlay_files'] = ['release/src/router/example.c']
        overlay = self.platform / 'source-overlay/release/src/router/example.c'
        overlay.parent.mkdir(parents=True)
        overlay.write_text('platform source\n')
        native.materialize(self.repo, self.build, self.plan())
        self.assertEqual((self.build / 'source/release/src/router/example.c').read_text(), 'platform source\n')
        self.assertEqual(self.common.read_text(), 'common source\n')

    def test_removed_inputs_require_clean(self):
        native.materialize(self.repo, self.build, self.plan())
        self.manifest['shared_files'] = []
        with self.assertRaisesRegex(ValueError, 'run make clean'):
            native.materialize(self.repo, self.build, self.plan())

    def test_rejects_path_escape_and_symlink_ancestor(self):
        self.manifest['shared_files'] = ['../outside']
        with self.assertRaises(ValueError):
            self.plan()
        self.manifest['shared_files'] = ['release/src/router/example.c']
        self.manifest['platform_links'] = {'../src': '../../outside'}
        with self.assertRaises(ValueError):
            self.plan()
        self.manifest['shared_files'] = ['release/src/router/example.c']
        self.manifest['platform_links'] = {}
        self.manifest['overlay_files'] = ['release/src/router']
        overlay = self.platform / 'source-overlay/release/src/router'
        overlay.parent.mkdir(parents=True)
        overlay.symlink_to('/outside')
        with self.assertRaisesRegex(ValueError, 'below a symlink'):
            self.plan()


if __name__ == '__main__':
    unittest.main()
